-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 02:38:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sekolah
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sekolah` ;

-- -----------------------------------------------------
-- Schema sekolah
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sekolah` DEFAULT CHARACTER SET utf8 ;
USE `sekolah` ;

-- -----------------------------------------------------
-- Table `sekolah`.`pengguna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`pengguna` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nama_pengguna` VARCHAR(32) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `sandi` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nama_pengguna_UNIQUE` (`nama_pengguna` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`biodata_siswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`biodata_siswa` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nama_lengkap` VARCHAR(256) NOT NULL,
  `tanggal_lahir` DATE NOT NULL,
  `tempat_lahir` VARCHAR(64) NOT NULL,
  `alamat` TEXT NOT NULL,
  `no_telp` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `no_telp_UNIQUE` (`no_telp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`jenis_guru`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`jenis_guru` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`biodata_guru`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`biodata_guru` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nama_lengkap` VARCHAR(256) NOT NULL,
  `tanggal_lahir` DATE NOT NULL,
  `tempat_lahir` VARCHAR(64) NOT NULL,
  `alamat` TEXT NOT NULL,
  `no_telp` VARCHAR(32) NOT NULL,
  `no_ktp` VARCHAR(16) NOT NULL,
  `no_sertifikat_pendidik` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `no_telp_UNIQUE` (`no_telp` ASC),
  UNIQUE INDEX `no_ktp_UNIQUE` (`no_ktp` ASC),
  UNIQUE INDEX `no_sertifikat_pendidik_UNIQUE` (`no_sertifikat_pendidik` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`guru`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`guru` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pengguna_id` BIGINT NOT NULL,
  `no_induk` VARCHAR(45) NULL,
  `biodata_guru_id` BIGINT NOT NULL,
  `jenis_guru_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pengguna_id`, `jenis_guru_id`),
  INDEX `fk_guru_jenis_guru1_idx` (`jenis_guru_id` ASC),
  INDEX `fk_guru_biodata_guru1_idx` (`biodata_guru_id` ASC),
  INDEX `fk_guru_pengguna1_idx` (`pengguna_id` ASC),
  UNIQUE INDEX `no_induk_UNIQUE` (`no_induk` ASC),
  CONSTRAINT `fk_guru_jenis_guru1`
    FOREIGN KEY (`jenis_guru_id`)
    REFERENCES `sekolah`.`jenis_guru` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guru_biodata_guru1`
    FOREIGN KEY (`biodata_guru_id`)
    REFERENCES `sekolah`.`biodata_guru` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guru_pengguna1`
    FOREIGN KEY (`pengguna_id`)
    REFERENCES `sekolah`.`pengguna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`kelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`kelas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(18) NOT NULL,
  `walikelas_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kelas_guru1_idx` (`walikelas_id` ASC),
  CONSTRAINT `fk_kelas_guru1`
    FOREIGN KEY (`walikelas_id`)
    REFERENCES `sekolah`.`guru` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`raport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`raport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `catatan_wali_kelas` TEXT NULL,
  `jumlah_alpha` INT NULL,
  `jumlah_sakit` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`siswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`siswa` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pengguna_id` BIGINT NOT NULL,
  `no_induk` VARCHAR(45) NULL,
  `biodata_siswa_id` BIGINT NOT NULL,
  `raport_id` INT NOT NULL,
  `kelas_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `pengguna_id`, `raport_id`, `kelas_id`),
  INDEX `fk_siswa_pengguna1_idx` (`pengguna_id` ASC),
  INDEX `fk_siswa_biodata_siswa1_idx` (`biodata_siswa_id` ASC),
  INDEX `fk_siswa_kelas1_idx` (`kelas_id` ASC),
  INDEX `fk_siswa_raport1_idx` (`raport_id` ASC),
  UNIQUE INDEX `no_induk_UNIQUE` (`no_induk` ASC),
  CONSTRAINT `fk_siswa_pengguna1`
    FOREIGN KEY (`pengguna_id`)
    REFERENCES `sekolah`.`pengguna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_siswa_biodata_siswa1`
    FOREIGN KEY (`biodata_siswa_id`)
    REFERENCES `sekolah`.`biodata_siswa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_siswa_kelas1`
    FOREIGN KEY (`kelas_id`)
    REFERENCES `sekolah`.`kelas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_siswa_raport1`
    FOREIGN KEY (`raport_id`)
    REFERENCES `sekolah`.`raport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`tahun_ajaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`tahun_ajaran` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nama_UNIQUE` (`nama` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`semester` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tahun_ajaran_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `tahun_ajaran_id`),
  INDEX `fk_semester_tahun_ajaran1_idx` (`tahun_ajaran_id` ASC),
  CONSTRAINT `fk_semester_tahun_ajaran1`
    FOREIGN KEY (`tahun_ajaran_id`)
    REFERENCES `sekolah`.`tahun_ajaran` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`jenis_pelajaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`jenis_pelajaran` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`pelajaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`pelajaran` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `kelas_id` BIGINT NOT NULL,
  `jenis_pelajaran_id` INT NOT NULL,
  `semester_id` BIGINT NOT NULL,
  `guru_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `jenis_pelajaran_id`, `semester_id`),
  INDEX `fk_pelajaran_semester1_idx` (`semester_id` ASC),
  INDEX `fk_pelajaran_jenis_pelajaran1_idx` (`jenis_pelajaran_id` ASC),
  INDEX `fk_pelajaran_kelas1_idx` (`kelas_id` ASC),
  INDEX `fk_pelajaran_guru1_idx` (`guru_id` ASC),
  CONSTRAINT `fk_pelajaran_semester1`
    FOREIGN KEY (`semester_id`)
    REFERENCES `sekolah`.`semester` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelajaran_jenis_pelajaran1`
    FOREIGN KEY (`jenis_pelajaran_id`)
    REFERENCES `sekolah`.`jenis_pelajaran` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelajaran_kelas1`
    FOREIGN KEY (`kelas_id`)
    REFERENCES `sekolah`.`kelas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelajaran_guru1`
    FOREIGN KEY (`guru_id`)
    REFERENCES `sekolah`.`guru` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`nilai_akhir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`nilai_akhir` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `raport_id` INT NOT NULL,
  `pelajaran_id` BIGINT NOT NULL,
  `pembilangan` FLOAT NOT NULL,
  `catatan` TEXT NULL,
  PRIMARY KEY (`id`, `raport_id`, `pelajaran_id`),
  INDEX `fk_nilai_akhir_pelajaran1_idx` (`pelajaran_id` ASC),
  INDEX `fk_nilai_akhir_raport1_idx` (`raport_id` ASC),
  CONSTRAINT `fk_nilai_akhir_pelajaran1`
    FOREIGN KEY (`pelajaran_id`)
    REFERENCES `sekolah`.`pelajaran` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nilai_akhir_raport1`
    FOREIGN KEY (`raport_id`)
    REFERENCES `sekolah`.`raport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sekolah`.`calon_siswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sekolah`.`calon_siswa` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pengguna_id` BIGINT NOT NULL,
  `no_pendaftaran` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `pengguna_id`),
  INDEX `fk_calon_siswa_pengguna1_idx` (`pengguna_id` ASC),
  UNIQUE INDEX `no_pendaftaran_UNIQUE` (`no_pendaftaran` ASC),
  CONSTRAINT `fk_calon_siswa_pengguna1`
    FOREIGN KEY (`pengguna_id`)
    REFERENCES `sekolah`.`pengguna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sekolah`.`jenis_guru`
-- -----------------------------------------------------
START TRANSACTION;
USE `sekolah`;
INSERT INTO `sekolah`.`jenis_guru` (`id`, `nama`) VALUES (1, 'Tata Usaha');
INSERT INTO `sekolah`.`jenis_guru` (`id`, `nama`) VALUES (2, 'Pelajaran');
INSERT INTO `sekolah`.`jenis_guru` (`id`, `nama`) VALUES (3, 'Wali Kelas');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sekolah`.`tahun_ajaran`
-- -----------------------------------------------------
START TRANSACTION;
USE `sekolah`;
INSERT INTO `sekolah`.`tahun_ajaran` (`id`, `nama`) VALUES (1, '2017/2018');
INSERT INTO `sekolah`.`tahun_ajaran` (`id`, `nama`) VALUES (2, '2018/2019');
INSERT INTO `sekolah`.`tahun_ajaran` (`id`, `nama`) VALUES (3, '2019/2020');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sekolah`.`jenis_pelajaran`
-- -----------------------------------------------------
START TRANSACTION;
USE `sekolah`;
INSERT INTO `sekolah`.`jenis_pelajaran` (`id`, `nama`) VALUES (1, 'Bahasa Indonesia');
INSERT INTO `sekolah`.`jenis_pelajaran` (`id`, `nama`) VALUES (2, 'Pendidikan Agama');
INSERT INTO `sekolah`.`jenis_pelajaran` (`id`, `nama`) VALUES (3, 'Pendidikan Kewarganegaraan');
INSERT INTO `sekolah`.`jenis_pelajaran` (`id`, `nama`) VALUES (4, 'Sejarah');
INSERT INTO `sekolah`.`jenis_pelajaran` (`id`, `nama`) VALUES (5, 'Matematika');

COMMIT;

